### ISSUE TITLE
Load lightbox error

### ISSUE THREAD

**Issue by unimaginativeGitHub** [jfcaiceo/react-lightbox-component#13]
I've implemented a basic single photo array as shown in the example, here's my:

``` javascript
    const images = [ {
      src: 'my-file-path.jpg',
      title: 'Cool Cat Photo!',
      description: 'No, really, cool cat photo!'
    } ];
   ...

   render = () => ...

   ...

   <Lightbox images={images}/>
```

I see the photo thumbnail, however when I click on the photo, I get little untitled buttons pop up around the thumbnail (I assume those are the zoom controls etc), no lightbox effect and I also get this error:
`invariant.js:38 Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's`render`method, or you have multiple copies of React loaded`

Before trying to implement this component, I've been using the bootstrap 'Thumbnail' tag to show this photo with no issues.

Is there something I can do to 'fix' my issue?  Has anyone else had this type of problem?

Thanks!

**Comment by vinaygunnam** [comment]
This error is due to multiple copies of "react" being pulled down during "npm install". This is happening because the "package.json" for this library lists "react" under "dependecies" instead of 
- "devDependencies" in case npm < v3
- "peerDependencies" in case of npm >= v3

Until the package.json is fixed, there are several workarounds suggested by other repos like this one:
- https://gist.github.com/jimfb/4faa6cbfb1ef476bd105#gistcomment-1746035

**Comment by jfcaiceo** [comment]
Thanks @vinaygunnam! I'll fix it this weekend and upload a new version to npm.

**Comment by pedroresende** [comment]
@jfcaiceo When do you expect to have this fixed ?

**Comment by acomito** [comment]
I'm still getting this as well

**Comment by variousauthors** [comment]
I am also experiencing this issue.

**Comment by jfcaiceo** [comment]
Fixed in the lastest release.
